=== poboxbrian/VariousProjects/RiskAssessment/schemas/input_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Patient",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "firstName": {
            "type": "string"
        },
        "lastName": {
            "type": "string"
        },
        "dateOfBirth": {
            "type": "string",
            "pattern": "\\d{4}-\\d{2}-\\d{2}"
        },
        "gender": {
            "$ref": "#/definitions/gender"
        },
        "cancers": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/cancer"
            }
        },
        "family": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/familyMember"
            }
        },
        "motherId": {
            "type": [
                "string",
                "null"
            ]
        },
        "fatherId": {
            "type": [
                "string",
                "null"
            ]
        }
    },
    "definitions": {
        "gender": {
            "type": "string",
            "enum": [
                "female",
                "male"
            ]
        },
        "cancer": {
            "type": "object",
            "properties": {
                "cancerType": {
                    "type": "string",
                    "enum": [
                        "brain",
                        "breast",
                        "colorectal",
                        "endometrial",
                        "gastric",
                        "kidney"
                    ]
                },
                "ageOfDiagnosis": {
                    "type": "integer"
                }
            },
            "required": [
                "cancerType"
            ]
        },
        "familyMember": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "motherId": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "fatherId": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "gender": {
                    "$ref": "#/definitions/gender"
                },
                "relationship": {
                    "type": "string",
                    "enum": [
                        "brother",
                        "daughter",
                        "father",
                        "granddaughter",
                        "grandson",
                        "maternal aunt",
                        "maternal first cousin",
                        "maternal grandfather",
                        "maternal grandmother",
                        "maternal half brother",
                        "maternal half sister",
                        "maternal uncle",
                        "mother",
                        "other",
                        "paternal aunt",
                        "paternal first cousin",
                        "paternal grandfather",
                        "paternal grandmother",
                        "paternal half brother",
                        "paternal half sister",
                        "paternal uncle",
                        "sister",
                        "son"
                    ]
                },
                "cancers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cancer"
                    }
                }
            },
            "required": [
                "id",
                "gender",
                "motherId",
                "fatherId",
                "relationship"
            ]
        }
    },
    "required": [
        "gender",
        "id",
        "motherId",
        "fatherId"
    ]
}

=== poboxbrian/VariousProjects/RiskAssessment/examples/input/patient_05.json
{
    "id": "patient",
    "gender": "female",
    "motherId": "mom",
    "fatherId": "dad",
    "family": [{
            "id": "mom",
            "gender": "female",
            "motherId": null,
            "fatherId": null,
            "relationship": "mother"
        },
        {
            "id": "dad",
            "gender": "male",
            "motherId": "grandma",
            "fatherId": "grandpa",
            "relationship": "father"
        },
        {
            "id": "grandpa",
            "gender": "male",
            "motherId": null,
            "fatherId": null,
            "relationship": "paternal grandfather",
            "cancers": [{
                "cancerType": "gastric"
            }]
        },
        {
            "id": "grandma",
            "gender": "female",
            "motherId": null,
            "fatherId": null,
            "relationship": "paternal grandmother",
            "cancers": [{
                "cancerType": "kidney"
            }]
        }
    ]
}

=== poboxbrian/VariousProjects/RiskAssessment/examples/input/patient_04.json
{
    "id": "patient",
    "gender": "female",
    "motherId": "mom",
    "fatherId": "dad",
    "family": [{
            "id": "mom",
            "gender": "female",
            "motherId": null,
            "fatherId": null,
            "relationship": "mother"
        },
        {
            "id": "dad",
            "gender": "male",
            "motherId": null,
            "fatherId": null,
            "relationship": "father"
        },
        {
            "id": "stepmom",
            "gender": "female",
            "motherId": null,
            "fatherId": null,
            "relationship": "other"
        },
        {
            "id": "halfbro",
            "gender": "male",
            "motherId": "stepmom",
            "fatherId": "dad",
            "relationship": "paternal half brother",
            "cancers": [{
                "cancerType": "breast"
            }]
        }
    ]
}

=== poboxbrian/VariousProjects/RiskAssessment/examples/input/patient_03.json
{
    "id": "abc123",
    "motherId": "mama",
    "fatherId": "papa",
    "firstName": "John",
    "lastName": "CancerIQ",
    "gender": "male",
    "dateOfBirth": "1950-03-25",
    "cancers": [{
        "cancerType": "brain"
    }],
    "family": [{
            "id": "papa",
            "motherId": "granny",
            "fatherId": null,
            "relationship": "father",
            "gender": "male"
        },
        {
            "id": "mama",
            "age": 77,
            "motherId": null,
            "fatherId": null,
            "relationship": "mother",
            "gender": "female",
            "cancers": [{
                "cancerType": "breast",
                "ageOfDiagnosis": 50
            }]
        },
        {
            "id": "granny",
            "motherId": null,
            "fatherId": null,
            "relationship": "paternal grandmother",
            "gender": "female"
        }
    ]
}
